- name: git is installed
  yum: name=git state=latest
  tags: ruby

- name: middlewares for building ruby are installed
  yum: 
    name: bzip2, gcc, openssl-devel, readline-devel, zlib-devel, gcc-c++, make
    state: latest
  tags: ruby

- name: ruby install directory is exists
  file: path={{rbenv_install_dir}} owner=root group=root mode=0700 state=directory
  tags: ruby

- name: rbenv are cloned 
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: "{{rbenv_install_dir}}/rbenv"
  tags: ruby

- name: ruby-build plugin are cloned 
  git: 
    repo: https://github.com/sstephenson/ruby-build.git 
    dest: "{{rbenv_install_dir}}/rbenv/plugins/ruby-build"
  tags: ruby

- name: ruby-build install.sh is executed
  command: 
    cmd: rbenv/plugins/ruby-build/install.sh
    chdir: "{{rbenv_install_dir}}"
  tags: ruby

- name: rbenv owner is set to app_owner 
  file: path={{rbenv_install_dir}}/rbenv owner={{app_owner}} group={{app_owner}} recurse=yes state=directory
  tags: ruby

- name: rbenv.sh is exist
  copy: src="rbenv.sh" dest="/etc/profile.d/rbenv.sh" owner=root group=root mode=0755
  tags: ruby

- name: rbenv.sh is loaded
  command: 
    cmd: /etc/profile.d/rbenv.sh
  tags: ruby

- name: specified ruby version is installed 
  command: 
    cmd: "rbenv install -s {{ruby_version}}"
  tags: ruby

- name: specified ruby version is avaiable 
  command: 
    cmd: "rbenv global {{ruby_version}}"
  tags: ruby

- name: bundler installed 
  gem:
    name: bundler
    user_install: no 
    executable: "{{rbenv_install_dir}}/rbenv/shims/gem"
  tags: ruby

- name: app-directory is exists
  file: path={{app_dir}} state=directory owner={{app_owner}} group={{app_group}} mode=0775
  tags: ruby

- name: app-directory owner is app_owner
  file: path={{app_dir}}/current state=directory owner={{app_owner}} group={{app_group}} recurse=yes
  tags: ruby
