#--------------------------------------------
# 1. rubyビルド用モジュールインストール
#--------------------------------------------
- name: install dependencies
  yum: 
    name: git, bzip2, gcc, openssl-devel, readline-devel, zlib-devel, gcc-c++, make
    state: latest
  tags: ruby

#---------------------------------------------------
# 2. RubyGem取得先のホスト定義（名前解決エラーに対処）
#---------------------------------------------------
- name: define rubygem repository hosts 
  copy: src="hosts" dest="/etc/hosts" owner=root group=root mode=0644
  tags: ruby

#---------------------------------------------------------------
# 3. Rubyのバージョンチェック
#     - 実行結果はokに固定, stdoutに出力されるバージョンで判定
#---------------------------------------------------------------
- name: specified ruby version is installed
  shell: bash -lc "ruby --version"
  register: result01
  changed_when: no
  failed_when: no
  tags: ruby

#---------------------------------------------------
# （3項デバッグ用）
#---------------------------------------------------
#- name: result01_debug
#  debug:
#    msg: "{{ result01 }}"
#  tags: ruby

#-----------------------------------------------------------------
# 4. Rubyインストール
#     - 条件： 3項で取得したバージョンが指定バージョンと異なる場合
#-----------------------------------------------------------------
- name: rbenv and ruby install
  block:
    #---------------------------------------
    # 4.1 rbenvインストールディレクトリ作成
    #---------------------------------------
    - name: rbenv install dir
      file: path={{rbenv_install_dir}} owner=root group=root mode=0755 state=directory
    #-----------------------
    # 4.2 rbenvインストール
    #-----------------------
    - name: rbenv repo
      git: repo=https://github.com/sstephenson/rbenv.git dest="{{rbenv_install_dir}}/rbenv"
    #---------------------------
    # 4.3 ruyb-buildインストール
    #---------------------------
    - name: ruby-build repo
      git: repo=https://github.com/sstephenson/ruby-build.git dest="{{rbenv_install_dir}}/rbenv/plugins/ruby-build"
    #------------------------------
    # 4.4 rbenvのオーナグループ変更
    #------------------------------
    - name: change rbenv owner 
      file: path={{rbenv_install_dir}}/rbenv owner={{app_owner}} group={{app_owner}} recurse=yes state=directory
    #---------------------------------------
    # 4.5 全ユーザ用rbenvパス設定ファイル作成
    #---------------------------------------
    - name: copy rbenv.sh
      copy: src="rbenv.sh" dest="/etc/profile.d/rbenv.sh" owner=root group=root mode=0755
    #------------------------------
    # 4.6 ruby-build実行/設定
    #------------------------------
    - name: ruby-build install-sh
      command: bash -lc "rbenv/plugins/ruby-build/install.sh" chdir="{{rbenv_install_dir}}"
    - name: load rbenv.sh
      command: bash -lc "source /etc/profile.d/rbenv.sh"
    #------------------------------
    # 4.7 指定のrubyバージョンインストール
    #------------------------------
    - name: install specified ruby version
      command: bash -lc "rbenv install -s {{ruby_version}}"
    #------------------------------
    # 4.8 rubyバージョン設定
    #------------------------------
    - name: install specified ruby version global
      command: bash -lc "rbenv global {{ruby_version}}"
    #------------------------------
    # 4.9 bundlerインストール
    #------------------------------
    - name: bundler installed 
      gem:
        name: bundler
        user_install: no 
        executable: "{{rbenv_install_dir}}/rbenv/shims/gem"
        version: 2.3.7
  when: ruby_version not in result01.stdout
  tags: ruby
