#---------------------------------------
# 1. ユーザ追加（app_owner）
#     - 実行ユーザ：root
#---------------------------------------
- name: add user (app-owner) 
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}}
  with_items: "{{users}}"
  tags: users

#---------------------------------------
# 2. 鍵認証用ディレクトリ作成
#     - 実行ユーザ：root
#---------------------------------------
- name: ~/.ssh for users exsit
  file: path="/home/{{item.name}}/.ssh" state=directory owner={{item.name}} group={{item.name}} mode=0700
  with_items: "{{users}}"
  tags: users

#---------------------------------------
# 3. SSH接続設定（公開鍵コピー）
#     - 実行ユーザ：root
#---------------------------------------
- name: authorized keys is deployed
  copy: src="authorized_keys_for_user" dest="/home/{{item.name}}/.ssh/authorized_keys" owner={{item.name}} group={{item.name}} mode=0600
  with_items: "{{users}}"
  tags: users

#---------------------------------------
# 4. sudo設定
#     - 実行ユーザ：root
#---------------------------------------
- name: sudo configured
  copy: src="sudoers" dest="/etc/sudoers" owner=root group=root mode=0440
  tags: users

#---------------------------------------
# 5. sudoユーザ追加設定(root)
#     - 実行ユーザ：root
#---------------------------------------
- name: sudo configured for root
  user: name=root groups=wheel state=present
  tags: users