- name: Setup nodejs12.x
  shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
  tags: yarn

- name: Install yarn package
  get_url: url="https://dl.yarnpkg.com/rpm/yarn.repo" dest=/etc/yum.repos.d/yarn.repo
  tags: yarn

- name: Installing yarn
  yum:
    name: yarn
    state: latest
    lock_timeout: 180
  tags: yarn
