---
- name: Install app-user, mysql-client, ruby, smr2-app, unicorn, nginx
  hosts: app_servers
  gather_facts: no
  remote_user: ec2-user

  roles:
    - common
    - mysql-client
    - nodejs-yarn
    - ruby
    - smr2-app