#---------------------------------------
# 1. community-releaseのリポジトリ追加
#     - 実行ユーザ：root
#---------------------------------------
- name: add mysql repository
  yum: 
    name: "{{mysql_package_url}}"
    state: latest
  tags: mysql-client

#---------------------------------------
# 2. mysql-community-clientインストール
#     - 実行ユーザ：root
#---------------------------------------
- name: install mysql-community-client
  yum: 
    name: mysql-community-client
    state: latest
  tags: mysql-client

#---------------------------------------
# 3. mysql-community-develインストール
#     - 実行ユーザ：root
#---------------------------------------
- name: install mysql-community-devel
  yum:
    name: mysql-community-devel
    state: latest
  tags: mysql-client
